export type HobbyDetail = {
  name: string;
  cost: 'free' | 'low' | 'medium' | 'high';
  timePerSession: string;
  socialLevel: 'solo' | 'optional' | 'social' | 'team';
  difficulty: 'easy' | 'moderate' | 'challenging';
  physical: 'none' | 'light' | 'moderate' | 'intense';
  indoor: boolean;
  outdoor: boolean;
  gear: string;
  bestFor: string;
};

export const HOBBY_DETAILS: Record<string, HobbyDetail> = {
  Drawing: {
    name: 'Drawing',
    cost: 'free',
    timePerSession: '30 min – 2 hours',
    socialLevel: 'solo',
    difficulty: 'easy',
    physical: 'none',
    indoor: true,
    outdoor: true,
    gear: 'Pencil and paper',
    bestFor: 'Stress relief and creative expression',
  },
  Painting: {
    name: 'Painting',
    cost: 'medium',
    timePerSession: '1 – 3 hours',
    socialLevel: 'solo',
    difficulty: 'moderate',
    physical: 'none',
    indoor: true,
    outdoor: true,
    gear: 'Paints, brushes, canvas',
    bestFor: 'Deep creative flow and artistic skill-building',
  },
  Photography: {
    name: 'Photography',
    cost: 'medium',
    timePerSession: '1 – 4 hours',
    socialLevel: 'optional',
    difficulty: 'moderate',
    physical: 'light',
    indoor: true,
    outdoor: true,
    gear: 'Camera or smartphone',
    bestFor: 'Capturing moments and seeing the world differently',
  },
  Writing: {
    name: 'Writing',
    cost: 'free',
    timePerSession: '30 min – 2 hours',
    socialLevel: 'solo',
    difficulty: 'moderate',
    physical: 'none',
    indoor: true,
    outdoor: true,
    gear: 'Pen and paper or laptop',
    bestFor: 'Self-expression and clarifying your thoughts',
  },
  Guitar: {
    name: 'Guitar',
    cost: 'medium',
    timePerSession: '30 min – 1 hour',
    socialLevel: 'optional',
    difficulty: 'moderate',
    physical: 'none',
    indoor: true,
    outdoor: true,
    gear: 'Guitar ($50–200 used)',
    bestFor: 'Musical expression and social bonding',
  },
  Piano: {
    name: 'Piano',
    cost: 'high',
    timePerSession: '30 min – 1 hour',
    socialLevel: 'optional',
    difficulty: 'challenging',
    physical: 'none',
    indoor: true,
    outdoor: false,
    gear: 'Piano or keyboard ($100+ for keyboard)',
    bestFor: 'Discipline, musicality, and classical artistry',
  },
  Drums: {
    name: 'Drums',
    cost: 'high',
    timePerSession: '30 min – 1 hour',
    socialLevel: 'optional',
    difficulty: 'moderate',
    physical: 'moderate',
    indoor: true,
    outdoor: false,
    gear: 'Drum kit or practice pad ($200+)',
    bestFor: 'Rhythm, energy release, and band collaboration',
  },
  Running: {
    name: 'Running',
    cost: 'low',
    timePerSession: '20 min – 1 hour',
    socialLevel: 'optional',
    difficulty: 'moderate',
    physical: 'intense',
    indoor: false,
    outdoor: true,
    gear: 'Running shoes',
    bestFor: 'Cardiovascular health and mental clarity',
  },
  Cycling: {
    name: 'Cycling',
    cost: 'medium',
    timePerSession: '30 min – 3 hours',
    socialLevel: 'optional',
    difficulty: 'moderate',
    physical: 'intense',
    indoor: false,
    outdoor: true,
    gear: 'Bicycle and helmet ($150+ used)',
    bestFor: 'Endurance, exploration, and eco-friendly commuting',
  },
  Swimming: {
    name: 'Swimming',
    cost: 'low',
    timePerSession: '30 min – 1 hour',
    socialLevel: 'optional',
    difficulty: 'moderate',
    physical: 'intense',
    indoor: true,
    outdoor: true,
    gear: 'Swimwear and goggles',
    bestFor: 'Full-body fitness and low-impact recovery',
  },
  Hiking: {
    name: 'Hiking',
    cost: 'low',
    timePerSession: '2 – 6 hours',
    socialLevel: 'optional',
    difficulty: 'moderate',
    physical: 'moderate',
    indoor: false,
    outdoor: true,
    gear: 'Sturdy shoes and a water bottle',
    bestFor: 'Nature connection and mental reset',
  },
  Climbing: {
    name: 'Climbing',
    cost: 'medium',
    timePerSession: '1 – 3 hours',
    socialLevel: 'social',
    difficulty: 'challenging',
    physical: 'intense',
    indoor: true,
    outdoor: true,
    gear: 'Climbing shoes and harness (rent at gym)',
    bestFor: 'Problem-solving strength and community',
  },
  Yoga: {
    name: 'Yoga',
    cost: 'free',
    timePerSession: '20 min – 1 hour',
    socialLevel: 'optional',
    difficulty: 'easy',
    physical: 'moderate',
    indoor: true,
    outdoor: true,
    gear: 'Yoga mat ($15–30)',
    bestFor: 'Flexibility, mindfulness, and stress management',
  },
  Basketball: {
    name: 'Basketball',
    cost: 'low',
    timePerSession: '1 – 2 hours',
    socialLevel: 'team',
    difficulty: 'moderate',
    physical: 'intense',
    indoor: true,
    outdoor: true,
    gear: 'Basketball and court access',
    bestFor: 'Teamwork, athleticism, and competitive fun',
  },
  Tennis: {
    name: 'Tennis',
    cost: 'medium',
    timePerSession: '1 – 2 hours',
    socialLevel: 'social',
    difficulty: 'moderate',
    physical: 'intense',
    indoor: true,
    outdoor: true,
    gear: 'Racket ($30–80) and court access',
    bestFor: 'Hand-eye coordination and friendly competition',
  },
  Reading: {
    name: 'Reading',
    cost: 'free',
    timePerSession: '20 min – 2 hours',
    socialLevel: 'solo',
    difficulty: 'easy',
    physical: 'none',
    indoor: true,
    outdoor: true,
    gear: 'Books or e-reader',
    bestFor: 'Knowledge, empathy, and imagination',
  },
  Chess: {
    name: 'Chess',
    cost: 'free',
    timePerSession: '15 min – 1 hour',
    socialLevel: 'social',
    difficulty: 'challenging',
    physical: 'none',
    indoor: true,
    outdoor: true,
    gear: 'Chess board or phone app',
    bestFor: 'Strategic thinking and mental sharpness',
  },
  Coding: {
    name: 'Coding',
    cost: 'free',
    timePerSession: '1 – 4 hours',
    socialLevel: 'optional',
    difficulty: 'challenging',
    physical: 'none',
    indoor: true,
    outdoor: false,
    gear: 'Laptop',
    bestFor: 'Building things and career-relevant problem-solving',
  },
  'Language learning': {
    name: 'Language learning',
    cost: 'free',
    timePerSession: '20 min – 1 hour',
    socialLevel: 'optional',
    difficulty: 'challenging',
    physical: 'none',
    indoor: true,
    outdoor: true,
    gear: 'App or textbook',
    bestFor: 'Travel readiness and cognitive flexibility',
  },
  'Video games': {
    name: 'Video games',
    cost: 'medium',
    timePerSession: '1 – 3 hours',
    socialLevel: 'optional',
    difficulty: 'moderate',
    physical: 'none',
    indoor: true,
    outdoor: false,
    gear: 'Console or PC',
    bestFor: 'Entertainment, reflexes, and online community',
  },
  'Board games': {
    name: 'Board games',
    cost: 'medium',
    timePerSession: '1 – 3 hours',
    socialLevel: 'social',
    difficulty: 'moderate',
    physical: 'none',
    indoor: true,
    outdoor: true,
    gear: 'Board games ($20–50 each)',
    bestFor: 'Social bonding and strategic fun',
  },
  Gardening: {
    name: 'Gardening',
    cost: 'low',
    timePerSession: '30 min – 2 hours',
    socialLevel: 'solo',
    difficulty: 'easy',
    physical: 'light',
    indoor: true,
    outdoor: true,
    gear: 'Seeds, soil, and basic tools',
    bestFor: 'Patience, nurturing, and fresh produce',
  },
  'Bird watching': {
    name: 'Bird watching',
    cost: 'low',
    timePerSession: '1 – 3 hours',
    socialLevel: 'optional',
    difficulty: 'easy',
    physical: 'light',
    indoor: false,
    outdoor: true,
    gear: 'Binoculars and a field guide',
    bestFor: 'Mindful observation and nature appreciation',
  },
  Cooking: {
    name: 'Cooking',
    cost: 'medium',
    timePerSession: '30 min – 2 hours',
    socialLevel: 'optional',
    difficulty: 'moderate',
    physical: 'light',
    indoor: true,
    outdoor: false,
    gear: 'Kitchen and basic ingredients',
    bestFor: 'Creativity, nourishment, and impressing friends',
  },
  Baking: {
    name: 'Baking',
    cost: 'low',
    timePerSession: '1 – 3 hours',
    socialLevel: 'optional',
    difficulty: 'moderate',
    physical: 'light',
    indoor: true,
    outdoor: false,
    gear: 'Oven, mixing bowls, and baking supplies',
    bestFor: 'Precision, comfort, and sharing sweet results',
  },
  Woodworking: {
    name: 'Woodworking',
    cost: 'high',
    timePerSession: '2 – 5 hours',
    socialLevel: 'solo',
    difficulty: 'challenging',
    physical: 'moderate',
    indoor: true,
    outdoor: true,
    gear: 'Basic hand tools or power tools ($100+)',
    bestFor: 'Making tangible things that last a lifetime',
  },
  '3D printing': {
    name: '3D printing',
    cost: 'medium',
    timePerSession: '1 – 4 hours',
    socialLevel: 'optional',
    difficulty: 'moderate',
    physical: 'none',
    indoor: true,
    outdoor: false,
    gear: '3D printer ($200+) and filament',
    bestFor: 'Turning digital ideas into physical objects',
  },
  Knitting: {
    name: 'Knitting',
    cost: 'low',
    timePerSession: '30 min – 2 hours',
    socialLevel: 'optional',
    difficulty: 'easy',
    physical: 'none',
    indoor: true,
    outdoor: true,
    gear: 'Knitting needles and yarn ($10–20 to start)',
    bestFor: 'Meditative focus and creating wearable art',
  },
  Volunteering: {
    name: 'Volunteering',
    cost: 'free',
    timePerSession: '2 – 6 hours',
    socialLevel: 'social',
    difficulty: 'easy',
    physical: 'light',
    indoor: true,
    outdoor: true,
    gear: 'Nothing — just show up',
    bestFor: 'Community impact and a sense of purpose',
  },
  Dance: {
    name: 'Dance',
    cost: 'low',
    timePerSession: '1 – 2 hours',
    socialLevel: 'social',
    difficulty: 'moderate',
    physical: 'intense',
    indoor: true,
    outdoor: true,
    gear: 'Comfortable clothes and dance shoes',
    bestFor: 'Expression, coordination, and joyful movement',
  },
};

export const ALL_COMPARABLE_HOBBIES = Object.keys(HOBBY_DETAILS);
