import { readdir, readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";

const dist = new URL("../dist/", import.meta.url);
const assets = {};
const files = new Set(await readdir(new URL("landing/", dist)));
let html = (await readFile(new URL("index.html", dist), "utf8"))
  .replaceAll("https://significanthobbies.com", "__HUB_PUBLIC_ORIGIN__");
const content = JSON.parse(await readFile(new URL("../src/content/home.json", import.meta.url), "utf8"));
// Ship only the masthead's three normal faces: Newsreader, Figtree and mono labels.
if (content.page.theme === "paper") {
  for (const match of html.matchAll(/href="(\/landing\/[^" ]+\.css)"/g)) {
    const path = match[1];
    const css = (await readFile(new URL(path.slice(1), dist), "utf8"))
      .replace(/@font-face\{[^}]*\}/g, (face) =>
        /font-family:(?:Figtree Variable|Geist Mono Variable|Newsreader Display);font-style:normal;/.test(face) ? face : "");
    const file = `home.${createHash("sha256").update(css).digest("hex").slice(0, 12)}.css`;
    await writeFile(new URL(`landing/${file}`, dist), css);
    files.add(file);
    html = html.replaceAll(path, `/landing/${file}`);
  }
  // Preview and the Worker must use exactly the same HTML and styles.
  await writeFile(new URL("index.html", dist), html.replaceAll("__HUB_PUBLIC_ORIGIN__", "https://significanthobbies.com"));
}
// Only bundle reachable assets: Astro also emits unused React and motion chunks.
const pending = [...html.matchAll(/(?:href|src)="(\/landing\/[^" ]+)"/g)].map((match) => match[1]);
while (pending.length) {
  const path = pending.shift();
  if (assets[path]) continue;
  const file = path.slice("/landing/".length);
  if (file.includes("/") || !files.has(file)) {
    throw new Error(`Invalid landing asset: ${path}`);
  }
  const type = file.endsWith(".css")
    ? "text/css; charset=utf-8"
    : file.endsWith(".js")
      ? "text/javascript; charset=utf-8"
      : file.endsWith(".webp") ? "image/webp"
      : file.endsWith(".woff2") ? "font/woff2"
      : file.endsWith(".woff") ? "font/woff" : null;
  if (!type) throw new Error(`Unexpected landing asset: ${file}`);
  const binary = type.startsWith("font/") || type.startsWith("image/");
  const buffer = await readFile(new URL(`landing/${file}`, dist));
  const body = buffer.toString(binary ? "base64" : "utf8");
  assets[path] = {
    type,
    body,
    ...(binary && { base64: true }),
  };
  if (!binary) {
    pending.push(...[...body.matchAll(/\/landing\/[\w.-]+/g)].map((match) => match[0]));
  }
}
const output = new URL("../../services/hub-backend/src/landing.generated.ts", import.meta.url);
await writeFile(output, [
  "// Generated by pnpm --dir landing build. Edit landing/src/content/home.json or its page, then rebuild.",
  `export const LANDING_HTML = ${JSON.stringify(html)};`,
  `export const LANDING_ASSETS: Record<string, { type: string; body: string; base64?: boolean }> = ${JSON.stringify(assets)};`,
  "",
].join("\n"));
console.log(`Emitted ${fileURLToPath(output)} (${Object.keys(assets).length} assets)`);
