/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 19437b18687a13ae319ea19801575a6c)
interface __BaseEnv_Env {
	DB: D1Database;
	AUTH_MODE: "production";
	LOCAL_AUTH_TOKEN: "";
	LOCAL_AUTH_USER_ID: "";
	OWNER_TIMEZONE: "Asia/Kolkata";
	ALLOWED_ORIGINS: "https://sh.com,https://significanthobbies.com";
	AUTH_SERVICE: Fetcher /* significanthobbies */;
	CALORIE_SERVICE: Fetcher /* calorie */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_MODE" | "LOCAL_AUTH_TOKEN" | "LOCAL_AUTH_USER_ID" | "OWNER_TIMEZONE" | "ALLOWED_ORIGINS">> {}
}
